FROM public.ecr.aws/emr-serverless/spark/emr-6.15.0:latest

# FROM 117819748843.dkr.ecr.us-east-1.amazonaws.com/emr-serverless:latest

USER root

# EMRS will run the image as hadoop
USER hadoop:hadoop
