name: 'dbt_analytics'
version: '1.0.0'
config-version: 2

profile: 'dbt_analytics'

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  dbt_analytics:
    +materialized: table
