
name: Deploy Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - backend/**

env:
  AWS_REGION: "us-east-1"
  AWS_ACCOUNT_ID: "117819748843"
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  
permissions:
  contents: read

defaults:
 run:
  working-directory: backend/

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    environment: production
    container:
      image: public.ecr.aws/sam/build-python3.11:latest

    steps:
    - name: Checkout
      uses: taiki-e/checkout-action@v1

    - name: SAM build
      run: sam build
      
    - name: SAM deploy
      run: >
        sam deploy 
        --stack-name video-streams-api
        --region ${AWS_REGION}
        --no-fail-on-empty-changeset
        --capabilities CAPABILITY_AUTO_EXPAND
        --s3-bucket deployment-zone-${AWS_ACCOUNT_ID}
        --s3-prefix ${{ github.event.repository.name }}